name: Hit Agent API Cron

# Trigger schedule (every 10 minutes)
on:
  schedule:
    - cron: "*/10 * * * *" # every 10 minutes
  workflow_dispatch: # manual trigger option

jobs:
  hit-api:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API endpoint
        run: |
          echo "📡 Hitting API: https://my-agent-t5ic.onrender.com/health"
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://my-agent-t5ic.onrender.com/health)
          if [ "$RESPONSE" -eq 200 ]; then
            echo "✅ API is up! Status code $RESPONSE"
          else
            echo "❌ API returned $RESPONSE"
            exit 1
          fi
