name: API Health Check

# Trigger on schedule (every 1 minute) and on push (optional)
on:
  schedule:
    - cron: "* * * * *" # every 1 minute
  workflow_dispatch: # manual trigger

jobs:
  hit-api:
    runs-on: ubuntu-latest
    steps:
      - name: Hit API endpoint
        run: |
          echo "📡 Hitting API: https://my-agent-t5ic.onrender.com/health"
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://my-agent-t5ic.onrender.com/health || echo "000")
          echo "🔹 API responded with code: $HTTP_CODE"
        continue-on-error: true
